development:
  twitter_handle:     "rightboatdotcom"
  twitter_key:        "key"
  twitter_secret:     "secret"
  mongo_url:          "mongodb://127.0.0.1:27017/rightboat_development"
  captcha_salt:       "a78668d1cdf08b82d"
  aws_s3_access_key_id: "xxx"
  aws_s3_secret_access_key: "yyy"
  xero_consumer_key: "xxx"
  xero_consumer_secret: "yyy"
  xero_privatekey_filename: "privatekey_dev.pem"

staging:
  twitter_handle:     "rightboatdotcom"
  twitter_key:        "key"
  twitter_secret:     "secret"
  captcha_salt:       "a78668d1cdf08b82d"
  mongo_url:          "mongodb://127.0.0.1:27017/rightboat_production"
  aws_s3_access_key_id: "xxx"
  aws_s3_secret_access_key: "yyy"
  rb_host:             "staging.rightboat.com"

production:
  twitter_handle:     "rightboatdotcom"
  twitter_key:        "key"
  twitter_secret:     "secret"
  captcha_salt:       "a78668d1cdf08b82d"
  mongo_url:          "mongodb://127.0.0.1:27017/rightboat_production"
  aws_s3_access_key_id: "xxx"
  aws_s3_secret_access_key: "yyy"
  rb_host:             "live.rightboat.com"
