# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rightboat2_development

staging:
  <<: *default
  database: rightboat2
  username: rightboat
  password: <%= ENV['RIGHTBOAT_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: rightboat2
  username: rightboat
  password: <%= ENV['RIGHTBOAT_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: rightboat2_test

# for migrating v1 db
v1_development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rightboat_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

v1_production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rightboat
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

