development:
  sessions:
    default:
      database: rightboat_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: rightboat_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      database: rightboat_v2
      hosts:
        - 172.31.24.106:27017
      options:
  options:

staging:
  sessions:
    default:
      database: rightboat_v2
      hosts:
        - localhost:27017
      options:
  options:
