# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95f7f1d64647270eda3aca0e8ae5acd619112fbe77a8b72dc5a2e752f7a0f56ac2eb7f8aa07d8e530d078452a03b29525b20911017151d220fb104c9b325dcd0
  db_ip_key: 8b2279c16a7c342e42be3079e2ae7606cb111694
  proxymesh_user: xxx
  proxymesh_pass: yyy
  stripe_secret_key: "sk_test_HcS1P03XzyPFaclWmpEGjnA2"
  stripe_publishable_key: "pk_test_sVP4RkyussmlNRZIy5OD5Dlv"
  gmail_smtp:
    :authentication: "plain"
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "rightboat.com"
    :user_name: "XXX"
    :password: "XXX"
    :enable_starttls_auto: true
  amazon_smtp:
    :authentication: "plain"
    :address: "email-smtp.eu-west-1.amazonaws.com"
    :port: 587
    :domain: "rightboat.com"
    :user_name: "XXX"
    :password: "XXX"
    :enable_starttls_auto: true

test:
  secret_key_base: 95f7f1d64647270eda3aca0e8ae5acd619112fbe77a8b72dc5a2e752f7a0f56ac2eb7f8aa07d8e530d078452a03b29525b20911017151d220fb104c9b325dcd0
  db_ip_key: 8b2279c16a7c342e42be3079e2ae7606cb111694
  proxymesh_user: xxx
  proxymesh_pass: yyy
  stripe_secret_key: "sk_test_HcS1P03XzyPFaclWmpEGjnA2"
  stripe_publishable_key: "pk_test_sVP4RkyussmlNRZIy5OD5Dlv"
  gmail_smtp:
    :authentication: "plain"
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "rightboat.com"
    :user_name: "XXX"
    :password: "XXX"
    :enable_starttls_auto: true
  amazon_smtp:
    :authentication: "plain"
    :address: "email-smtp.eu-west-1.amazonaws.com"
    :port: 587
    :domain: "rightboat.com"
    :user_name: "XXX"
    :password: "XXX"
    :enable_starttls_auto: true

staging:
  secret_key_base: zzz
  db_ip_key: zzz
  proxymesh_user: xxx
  proxymesh_pass: yyy
  gmail_smtp:
    :authentication: "plain"
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "rightboat.com"
    :user_name: "XXX"
    :password: "XXX"
    :enable_starttls_auto: true
  amazon_smtp:
    :authentication: "plain"
    :address: "email-smtp.eu-west-1.amazonaws.com"
    :port: 587
    :domain: "rightboat.com"
    :user_name: "XXX"
    :password: "XXX"
    :enable_starttls_auto: true

production:
  secret_key_base: zzz
  db_ip_key: zzz
  proxymesh_user: xxx
  proxymesh_pass: yyy
  stripe_secret_key: xxx
  stripe_publishable_key: yyy
  gmail_smtp:
    :authentication: "plain"
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "rightboat.com"
    :user_name: "XXX"
    :password: "XXX"
    :enable_starttls_auto: true
  amazon_smtp:
    :authentication: "plain"
    :address: "email-smtp.eu-west-1.amazonaws.com"
    :port: 587
    :domain: "rightboat.com"
    :user_name: "XXX"
    :password: "XXX"
    :enable_starttls_auto: true
