#= require jquery
#= require jquery_ujs

#  require twitter/bootstrap/transition.js
#  require twitter/bootstrap/alert.js
#  require twitter/bootstrap/button.js
#  require twitter/bootstrap/carousel.js
#  require twitter/bootstrap/collapse.js
#  require twitter/bootstrap/dropdown.js
#  require twitter/bootstrap/modal.js
#  require twitter/bootstrap/tooltip.js
#  require twitter/bootstrap/popover.js
#  require twitter/bootstrap/scrollspy.js
#  require twitter/bootstrap/tab.js
#  require twitter/bootstrap/affix.js

#= require jquery-ui/slider
#  require jquery.ui.touch-punch
#= require selectize
#  require js-cookie
#  require slick.min
#  require photoswipe.min
#  require photoswipe-ui-default.min
#  require validetta
#  require cocoon
#  require_tree ./common
#= require common/utils
#= require application/selects
#= require application/slider
#= require_tree ./broker_iframe
